//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Web_Sell.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DeliverySlips
    {
        public int DeliverySlipID { get; set; }
        public string OrderID { get; set; }
        public System.DateTime DeliveryDate { get; set; }
    
        public virtual Orders Orders { get; set; }
    }
}
