//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Web_Sell.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ManagerLogin
    {
        public string AgentID { get; set; }
        public string Username { get; set; }
        public string Password { get; set; }
        public bool isAdmin { get; set; }
    
        public virtual Agents Agents { get; set; }
        public string LoginErrorMessage { get; set; }
    }
}
